[package]
name = "kite-public-call-demo"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace]

[dependencies]
lee_core = { git = "https://github.com/logos-blockchain/logos-execution-zone", rev = "47eba256479f6f785acbd138834340703cd03401", default-features = false }
risc0-zkvm = { version = "=3.0.5", default-features = false, features = ["std"] }

[patch.crates-io]
keccak = { git = "https://github.com/logos-blockchain/sponges", rev = "3a56e99771beedf04946eab21a4a62adc2951377" }

[profile.release]
lto = "thin"
panic = "abort"
